title: Lab Devices
description: One stop site for device manuals, repair guides, modifications and more!

theme: just-the-docs

url: http://antoniovazquezblanco.github.io/labdevices

color_scheme: dark
